title: Jason Terrance Wells - Portfolio
description: MD | MBA Candidate | Computer Science Student
theme: jekyll-theme-minimal 

author: Jason Terrance Wells
email: jwells@5AMsurgical.com 
github_username: jawe4972
linkedin_username: jason-wells-89176999

# Fix the baseurl and url
baseurl: "" 
url: "https://jawe4972.github.io/jawe4972_2.github.io"  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/  

# Collections
collections:
  posts:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Show future posts (important for your dated post)
future: true

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Timezone setting
timezone: America/New_York
