title: Jason Terrance Wells - Portfolio
description: MD | MBA Candidate | Computer Science Student
theme: jekyll-theme-minimal 

author: Jason Terrance Wells
email: jwells@5AMsurgical.com 
github_username: jawe4972
linkedin_username: jason-wells-89176999

# Fixed baseurl for GitHub Pages - should match your repository name
baseurl: "/jawe4972_2.github.io" 
url: "https://jawe4972.github.io"  

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink structure
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Timezone setting
timezone: America/New_York

# GitHub Pages settings
github:
  is_project_page: false
